### ISSUE TITLE
Remove ld warning on hcc use

### ISSUE THREAD

**Issue by cursedastronaut** [Jamesbarford/holyc-lang#119]
For the example "Hello World" file presented:
```holyc
U0 Main()
{
  "Hello world\n";
}
Main;
```
Upon compilation, the following output is given:
```txt
$ hcc hello_world.HC 
/usr/bin/ld: warning: /tmp/ccXqHci0.o: missing .note.GNU-stack section implies executable stack
/usr/bin/ld: NOTE: This behaviour is deprecated and will be removed in a future version of the linker
```
Using GNU's ld 2.42 compiled for Ubuntu and GCC 13.3.0 (Ubuntu 13.3.0-6ubuntu2~24.04).
Will check tonight if it happens on Arch.

**Comment by cursedastronaut** [comment]
Does not happen on Arch Linux with ld 2.43.0 and gcc 14.2.1

**Comment by Jamesbarford** [comment]
If this works with `ld 2.43.0` and not `ld 2.42` then I can add to the README the minimum version of `ld` required is `2.43.0`

**Comment by cursedastronaut** [comment]
That works ig hahaha-
It still compiles on 2.42,just with a warning
