### ISSUE TITLE
Make compiler work without installing to /usr

### ISSUE THREAD

**Issue by cursedastronaut** [Jamesbarford/holyc-lang#120]
If you just use `make -C ./build`, you cannot compile if you cannot access `/usr` as it will still look for files as if those were installed:
```txt
$ ./hcc hello_world.HC 
ERROR: Failed to open file: /usr/local/include/tos.HH
```

If there is a compiler option to specify the location of those files, such as `./src/holyc-lib/`, the `--help` option wasn't clear enough for me to figure it out.

**Comment by Jamesbarford** [comment]
I'm not sure I see the immediate use case? `make install` or `sudo make install` solves this.

**Comment by cursedastronaut** [comment]
True, but if I don't have root privileges (such as on non-rooted phone), I can't use it. It'd be nice if we could compile it with a prefix like GCC where the default prefix would be `/usr/local`

**Comment by xplshn** [comment]
> I see your point, presently this isn't something I will look into. However later down the line I'll consider it once the build process is generally less prototypey.
> 
> With regard to getting this working on a phone, in all likelihood we'd need to be targeting ARM which the compiler does not yet do.

I install my toolchains and compilers at /opt/toolchains, why not add a simple env variable that does this? I don't see it being so hard...

**Comment by Jamesbarford** [comment]
You can now set this like so:
```
make INSTALL_PREFIX=<where_ever>
make INSTALL_PREFIX=<where_ever> install
```

However everything will be installed like so:
```
$(INSTALL_PREFIX)/include
$(INSTALL_PREFIX)/lib
$(INSTALL_PREFIX)/bin
```
Where the header file `tos.HH` will be copied into `$(INSTALL_PREFIX)/include`. Or if you are using `CMake` directly then you can set `CMAKE_INSTALL_PREFIX`

**Comment by cursedastronaut** [comment]
Thanks!
