### ISSUE TITLE
"Failed to extract filename" error

### ISSUE THREAD

**Issue by mrunix00** [Jamesbarford/holyc-lang#35]
When I try to compile any HC file or even check HolyC compiler version I get this error:
```console
➜  ~ hcc --version
--version
main.c:114:getASMFileName       Failed to extract filename
➜  ~ hcc main.HC
main.HC
main.c:114:getASMFileName       Failed to extract filename
```

**Comment by Jamesbarford** [comment]
Thanks for this.

An oversight on my part, a file requires `./` so in your case it would be `hcc ./main.HC`. The logic is in `getASMFileName`. As for `--version` I have not yet implemented this

**Comment by Jamesbarford** [comment]
Going to mark this as done; the file path issue is now fixed. The `--version` is separate; there is no command implementing it and thus the compiler thinks it's compiling a source file. A better error I think will be thrown to. To properly fix this I would like to somehow have this read in from a text file, or some other mechanism,
