### ISSUE TITLE
prsasm.c:138:PrsAsmPunct "unexpected character"

### ISSUE THREAD

**Issue by Alistair007** [Jamesbarford/holyc-lang#37]
Windows Ubuntu WSL: `prsasm.c:138:PrsAsmPunct        line 10: Unexpected character`, caused by the `loggerpanic()` macro. Any fix?

**Comment by Jamesbarford** [comment]
Hmm. I've re-compiled the compiler on the `main` branch which in turn compiles ~4,000 lines of holyc with assembly and run the tests of which indicate no compiler errors linked with this message. Please correct me if wrong.

The error messages are, sadly for the moment, quite unfriendly and not terribly readable as it does not report the file name in which the error occurred. In this instance I believe the error is that you have a syntax error on line 10 inside and `asm` block, looking at the `PrsAsmPunct()` function shows that the offending character should have been printed along with this error message. If you are able to share your code I'm happy to have a look.

**Comment by Jamesbarford** [comment]
I'm going to mark this as closed. If the issue persists please create another ticket and we can dive into it!
