### ISSUE TITLE
"-tokens" compiler option results in segmentation fault

### ISSUE THREAD

**Issue by david-prv** [Jamesbarford/holyc-lang#42]
I'm playing around a little bit with HolyC and your compiler, just to get used to it. I wanted to dump the token list and have a look into it. To do so, I copied the [example](https://github.com/Jamesbarford/holyc-lang?tab=readme-ov-file#example) from your README and tried to compile it using the following command `hcc -tokens example.HC`. This results in a segmentation fault error.

**Comment by Jamesbarford** [comment]
Closed by pull request: #44
