### ISSUE TITLE
[Feature request] MinGW Support

### ISSUE THREAD

**Issue by Ena-Shepherd** [Jamesbarford/holyc-lang#53]
Hello,
I tried to port your project to MinGW without success.
It would be very nice to have access to your compiler on windows.
Have a good day !

**Comment by Jamesbarford** [comment]
Thank you for your comment.

Certainly I see the value of having this project of compiling on Windows as it is quite limiting having it only work for Mac and Linux `x86_64` machines. 

Presently this is not something I'm currently looking to do. When I have spare time to work on this I am expending my efforts on trying to make this compiler have an intermediate representation and subsequently target different architectures. Thus compiling on Windows is not something that will be done in the near future, it is however something I would consider later down the line. 

Though I do not have a windows computer to test this theory; you can install WSL2 (Windows Subsystem for Linux) and I'd have thought this would compile and work without much issue.

**Comment by Ena-Shepherd** [comment]
Thank you for your reply :)
I forked the project a few days ago to add some features,
and try again for MinGW.
IR is also a good plan imo.

The closest thing to being done right now is adding CMake to build hcc even more easily.

Adding GitHub actions for testing and producing releases will be planned too on my end.

Have a good day

**Comment by W1Real** [comment]
God Bless 🙏✝

**Comment by Jamesbarford** [comment]
Thanks for this, unfortunately making the compiler run on Windows is not something I aim to do in the immediate future. However if you have a patch with Windows support, please sumbit it and I will review 👍.

If you would like to use this compiler on Windows at the present time please [download WLS2](https://learn.microsoft.com/en-us/windows/wsl/install)

As an interim step I will update the documentation to point to using WSL2.

**Comment by Jamesbarford** [comment]
#64
