### ISSUE TITLE
ERROR: Ran out of tokens

### ISSUE THREAD

**Issue by ParkerrDev** [Jamesbarford/holyc-lang#62]
On any example HolyC program I've tried, when I go to compile it I will get an: 

`ERROR: line 7: Ran out of tokens`

on an obscure line number. 

The program:

```
U0 Function(U8 *name="Bob")
{
  "%s\n",name;
}

Function; 
Function("Terry");   
```

Any idea why this happens? Am I doing something wrong? How can I fix it?

**Comment by Jamesbarford** [comment]
Hi, thanks for this. What OS are you on? I've tried the above code on an intel mac and it works fine.

The global function calling mechanism is not as robust as having a main function, oftentimes wrapping your code in a `Main` can solve some issues:

```hc
U0 Main()
{
  U0 Function(U8 *name="Bob")
  {
    "%s\n",name;
  }

  Function; 
  Function("Terry");
}
```

**Comment by ParkerrDev** [comment]
I have tried it on both NixOS and a Fedora Linux Server, both had the same error. Both use intel processors. To debug it, maybe spin up a live Linux server somewhere?

**Comment by Jamesbarford** [comment]
I have now tried this on a couple different machines (Linux) and am not able to re-create this error.

I was going to ask what version of the compiler you are using, however I've not implemented versioning 😂. So all I can ask is are you using the code from the branch `main`?

**Comment by ParkerrDev** [comment]
Another issue worth noting:

When running the unit tests:

It initially didn't work and I had to install sqlite-devel, then the initial tests started to pass but it gets hung at 'Test - Simple Threading'

```
[parker@jarvis holyc-lang]$ make unit-test
make -C ./build unit-test
make[1]: Entering directory '/home/parker/holyc-lang/build'
[ 94%] Built target hcc
[100%] Building and running unit tests
Running unit tests...
Testing if else
PASSED: 4/4
=====
Test Assigning pointer to a pointer from a class, with brackets: PASSED: 1/1
====
Test Assigning pointer to a pointer from a class, no brackets: PASSED: 1/1
====
Test - Juggling an array MAlloc(I64 * 10): PASSED: 4/4
====
Test - Pointer to a pointer from a class: PASSED: 1/1
=====
Test - Taking the address of a local: PASSED: 1/1
Test - class definition: PASSED: 6/6
====
Test - Linked list recusive definition class: PASSED: 5/5
====
Test - 'break' and 'continue' inside while and for loops: PASSED: 4/4
====
Test - Default function parameters: PASSED: 1/1
====
Test - qsort, recursion and default function params: PASSED: 1/1
====
Assignment tests:
= test: PASSED: 2/2
+= test: PASSED: 2/2
-= test: PASSED: 2/2
*= test: PASSED: 2/2
/= test: PASSED: 2/2
%= test: PASSED: 2/2
&= test: PASSED: 2/2
|= test: PASSED: 2/2
^= test: PASSED: 2/2
>>= test: PASSED: 2/2
<<= test: PASSED: 2/2
=====
Test - Function pointers: PASSED: 5/5
====
Test - Simple Threading: 

```

After hittitng CTRL-C it skips the test and the rest seem to pass:

But it would hang there forever if I didn't. I wonder if this is a related to the token error problem. 🤔

```
^CFAILED to run: 13_threads.HC
Test Mathematics:
Subtraction - : PASSED: 7/7
Multiplication * : PASSED: 5/5
Modulo % : PASSED: 5/5
Addition + : PASSED: 5/5
Division / : PASSED: 3/3
MATHS_SHL << : PASSED: 3/3
MATHS_SHR >> : PASSED: 3/3
Xor ^: PASSED: 3/3
Or |: PASSED: 3/3
And &: PASSED: 3/3
Not ~: PASSED: 3/3
=====
Test - MemCpy, MemSet: PASSED: 4/4
Test - comma separated declarators & types: PASSED: 3/3
====
Test - Variable arguments: PASSED: 15/15
=====
Test - Type casting:
PASSED: 9/9
=====
Test - Switch statement: PASSED: 7/7
Loop test suite
Testing For Loop: PASSED: 2/2
Testing while loop: PASSED: 1/1
Testing do-while loop: PASSED: 1/1
=====
Testing GOTO: PASSED: 2/2
=====
Addressing: PASSED: 2/2
====
Malloced Arrays:
PASSED: 10/10
PASSED: 2/2
=====
Test: Union and class inheritance: PASSED: 4/4
====
Test Scripting: Test Scripting: PASSED: 4/4
===
Test - Floating point arithmetic:
PASSED: 5/5
====
Test - auto keyword: PASSED: 2/2
====
Test - Arrays & multi dimensional: PASSED: 4/4
====
Test - Preprocessor: PASSED: 6/6
====
Test - FzF fuzzy finding: PASSED: 7/7
====
Test - JSON parsing: {"hello": 10,"key": "some string","id": null,"bool2": false,"bool": true,"array": [1,30030303,430,-14]}
PASSED: 10/10
====
Test - sqlite bindings & abstraction: 
PASSED: 4/4
====
Test - local static variables and global variables: 
PASSED: 3/3
====
Test - Global and static array
PASSED: 2/2
====
Test - basic io: PASSED: 4/4
====
make[3]: *** [CMakeFiles/Makefile2:110: CMakeFiles/unit-test.dir/all] Interrupt
make[2]: *** [CMakeFiles/Makefile2:117: CMakeFiles/unit-test.dir/rule] Interrupt
make[1]: *** [Makefile:182: unit-test] Interrupt
make: *** [Makefile:18: unit-test] Interrupt
```

**Comment by Jamesbarford** [comment]
I've thought a bit about this.

For the threading error you are seeing in the tests; they too have been buggy on computers I have tested it on. I think this is going to be something to do with the rather poor assmebly code produced by the compiler and will eventually be ironed out.

With `sqlite` being required as a dependency. This does seem a bit odd as I can't imagine that is a particularly common usecase and led to a incomprehensive bug. As such I will add it as a compilation option and use an `#ifdef HOLYC_SQLITE` compile flag to enable / disable the use of it; this should make your original issue dissapear and results in a smaller binary for what I'd imagine to be most peoples use case.

**Comment by ParkerrDev** [comment]
Still seeing Ran out of tokens on latest commits. November 10, 2024:

[parker@jarvis ~]$ hcc ./main.HC 
ERROR: line 9: Ran out of tokens
[parker@jarvis ~]$

**Comment by Jamesbarford** [comment]
So clarify this error is for the following code:
```hc
U0 Function(U8 *name="Bob")
{
  "%s\n",name;
}

Function; 
Function("Terry");
```

**Comment by ParkerrDev** [comment]
Yes.

**Comment by Jamesbarford** [comment]
May you could please pull the latest code, recompile, reinstall and run:

```bash
hcc -tokens <file>.HC
```

And paste the output here? I've tried across a few computers now and _cannot_ recreate

**Comment by ParkerrDev** [comment]
The output is very long. I think it may be looping over and over? Causing it to exceed it memory limit or something? I've attached the output.txt.

I recompiled, reinstalled and ran:

```
[parker@jarvis test]$ cat main.HC
U0 Function(U8 *name="Bob")
{
  "%s\n",name;
}

Function; 
Function("Terry");
```

with command: `hcc -tokens main.HC > output.txt`

[output.txt](https://github.com/user-attachments/files/17692845/output.txt)

**Comment by ParkerrDev** [comment]
With your last commit I'm not getting a token error, but I'm not getting any output at all so idk? 🤷

```
[parker@jarvis test]$ hcc ./main.HC
[parker@jarvis test]$ cat main.HC
U0 Main()
{
  "Hello world\n";
}
Main;
[parker@jarvis test]$ 
```

**Comment by Jamesbarford** [comment]
Awesome! Seems like we're getting close.

By running `hcc ./<file>.HC` it should produce an `a.out` binary which you can then run.

Or if you want to have the illusion of JIT: `hcc -run <file>.HC`. I say illusion as under the hood it creates an `a.out`, executes the program and then deletes the `a.out` file.

Let me know if this works and then we can close the issue.

**Comment by ParkerrDev** [comment]
I forgot that its strictly compiles. I didn't see the a.out, I'm slow this morning. YES! It is working. Not sure what you did but it works now. Yay! 🥳

[parker@jarvis test]$ ls
a.out  holyc-lang  main.HC  output.txt
[parker@jarvis test]$ ./a.out
Hello world
[parker@jarvis test]$

**Comment by Jamesbarford** [comment]
Yahoo! Excellent. I'm sure I'll break something again very soon but I'm glad it's working for now!

**Comment by zkxjzmswkwl** [comment]
Same issue. Latest commit.

**Comment by Jamesbarford** [comment]
> Same issue. Latest commit.

Please file a new bug report with a code snippet. I've run the tests on the main branch on both MacOS and Ubuntu; all seems well.
